// User controller that we use whenever we want to display detailed
// information about a user
companionApp.controller('UserCtrl', function ($scope,$routeParams,$firebaseObject,Companion,$rootScope,$timeout,$location) {
  $scope.otherUser = Companion.getUser();

  var ref = new Firebase("https://companion-simulation.firebaseio.com");

  if ($routeParams.user) {
    var otherUserRef = ref.child('users/'+$routeParams.user);
  } else {
    var otherUserRef = null;
  }

  // Gives user a new monster
  $scope.hatchEgg = function() {
    if($scope.user.pokemon.isEgg === true) {
      Companion.getNewPokemon();
      $scope.nicknameSuccess = false;
      $scope.showNickname = true;
    }
  }

  // Sets a new name to user's monster
  $scope.addNickname = function(newNickname) {
    console.log("Nickname: ",newNickname);
    $scope.user.pokemon.name = newNickname.substring(0,20);
    $scope.showNickname = false;
    $scope.showAddNickname = false;
    $scope.nicknameSuccess = true;
    Companion.setUser($scope.user);
  }

  // Hides the create nickname popup
  $scope.hideNickname = function() {
    $scope.showNickname = false;
  }

  // Hides the nickname success popup
  $scope.hideNicknameSuccess = function() {
    $scope.nicknameSuccess = false;
  }

  $scope.challenge = function() {
    if (!$scope.user.challengers) {
      $scope.user.challengers = {};
    }
    // If already challenged by other user
    if ($scope.user.challengers[($scope.otherUser.uid)] && 
      $scope.user.challengers[($scope.otherUser.uid)].challengedYou) {
      // Return the other user's challenge
      otherUserRef.child('challengers/'+$scope.user.uid).update({
        challengedYou: true
      });
    }
    // If you already have challenged the user
    else if ($scope.user.challengers[($scope.otherUser.uid)] && 
      $scope.user.challengers[($scope.otherUser.uid)].challengedYou == false) {
      // Do something
    } else {
      // Put both users' uids in a child to battles in Firebase
      var user1 = {
        uid: $scope.user.uid,
        battleLog: false,
        here: false,
        winner: false
      };
      var user2 = {
        uid: $scope.otherUser.uid,
        battleLog: false,
        here: false,
        winner: false
      };
      newBattleRef = ref.child('battles').push({
        isEnded: false,
        user1,
        user2
      });
      // Get the unique ID generated by push()
      var newBattleRefID = newBattleRef.key();

      // Challenge other user
      otherUserRef.child('challengers/'+$scope.user.uid).set({
        name: $scope.user.name,
        sprite : $scope.user.pokemon.sprite,
        battleID: newBattleRefID,
        challengedYou: true
      });

      // Put other user in your challengers
      $scope.user.challengers[($scope.otherUser.uid)] = {
        name: $scope.otherUser.name,
        sprite : $scope.otherUser.pokemon.sprite,
        battleID: newBattleRefID,
        challengedYou: false
      };
      Companion.setUser($scope.user);
    }
  }

  // Attach an asynchronous callback to get otherUser when changed
  $scope.$on("userChanged", function() {
    if (!$routeParams.user) {
      // console.log("User changed, setting scope.otherUser!");
      $timeout(function() {
        $scope.otherUser = Companion.getUser();
      });
    }
  });

  // Change otherUserRef when otherUser has changed
  $scope.$on("otherUserChanged", function() {
    var uid = $location.path().substring($location.path().lastIndexOf('/')+1);

    if (otherUserRef) {
      otherUserRef.off("value");
    }

    // console.log("Setting otherUserRef!");
    otherUserRef = ref.child('users/'+uid);
    otherUserRef.on("value", function(snapshot) {
      $timeout(function() {
        $scope.otherUser = snapshot.val();
      });
    });
  });

  if ($routeParams.user) {
    otherUserRef.on("value", function(snapshot) {
      $timeout(function() {
        $scope.otherUser = snapshot.val();
        // console.log("otherUser:",$scope.otherUser);
      });
    });
  }

});
